name: Opustab-Merchant Automated Tests
on:
  schedule:
    - cron: '*/30 * * * *'  # Run daily at midnight
    # - cron: '0 2 * * *'
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
  

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    # timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.61.0-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.15.1'
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright tests
        run: npx playwright test
        env:
          CI: 'true'
          BASE_URL: 'https://merchant.opustab.com'  # Explicit URL
          # DEBUG: 'pw:api'  # Uncomment untuk debug detail
          
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: |
            playwright-report/
            test-results/
            test-results.json
          retention-days: 30
      
      - name: Configure GitHub pages
        if: always()
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Upload Artifact to GitHub Pages
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report

      - name: Deploy to GitHub Pages
        if: always()
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Send test report to Lark
        if: always()
        run: node scripts/send-lark.js
        env:
          LARK_WEBHOOK_URL: ${{ secrets.LARK_WEBHOOK_URL }}
          JOB_STATUS: ${{ job.status }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_SHA: ${{ github.sha }}
